import streamlit as st

# 1. قاموس المصطلحات والـ 13 حقل باللغة العربية
AR_DICTIONARY = {
    # الهيدر ولوحة التحكم العامة
    "platform_title": "منصة البناء المستدام",
    "platform_sub": "الحوكمة الرقمية والامتثال البيئي",
    "nav_title": "🎛️ لوحة التحكم السيادية للمنصة",
    "current_location": "الموقع الحالي",
    "lang_label": "اللغة",
    
    # أزرار الأبواب الستة الرئيسية
    "btn_portal_1": "🚪 الباب 1\nالتدقيق والتربة",
    "btn_portal_2": "🌱 الباب 2\nالطاقة والاستدامة",
    "btn_portal_3": "📊 الباب 3\nحصر المواد المركزي",
    "btn_portal_4": "🗺️ الباب 4\nخارطة GIS العراق",
    "btn_portal_5": "💳 الباب 5\nالبنية والمالية",
    "btn_portal_6": "🦺 الباب 6\nالسلامة الموقعية",
    
    # لوحة المؤشرات الاستراتيجية الجانبية
    "side_title": "📊 لوحة المؤشرات الحية",
    "compliance_score": "المطابقة الهندسية / Compliance",
    "integrity_score": "السلامة الإنشائية / Integrity",
    "energy_score": "استدامة الطاقة / Energy Score",
    
    # بوابة الهوية والمسؤولية القانونية
    "user_unregistered": "حساب غير مسجل",
    "user_action_verify": "اضغط لتأكيد الهوية",
    "drawer_title": "🔐 بوابة التوثيق والمسؤولية القانونية",
    "drawer_desc": "يجب إكمال رفع الهويات الرسمية لتتحمل المسؤولية القانونية الكاملة عن البيانات والمخططات الهندسية.",
    "lbl_user_name": "الاسم الرباعي الكامل للمخدم:",
    "lbl_user_role": "الصفة الفنية في المشروع:",
    "lbl_national_id": "رقم البطاقة الوطنية الموحدة (12 رقماً):",
    "lbl_syndicate_id": "رقم هوية نقابة المهندسين العراقية النافذة:",
    "lbl_upload_avatar": "ارفع صورتك الشخصية الرسمية (PNG/JPG):",
    "btn_submit_auth": "🔒 اعتماد وتوثيق الهوية وإطلاق الصلاحيات السيادية",
    "badge_verified": "🛡️ حساب موثق سيادياً ونقابياً | Professional Verified",
    "badge_desc": "المرتبة المعتمدة: مهندس استشاري مرخص",
    "crypto_notice": "*الحقول مشفرة عسكرياً بموجب AES-256 لحماية سرية المعلومات الشخصية.*",
    "btn_reset": "🔄 خروج وتصفير السجل التجريبي (Reset)",
    
    # البوابة الأولى: الـ 13 حقل والفلترة الجغرافية
    "title_p1": "📋 الباب الأول: تحليل الموقع ومحددات البلدية",
    "desc_p1": "يرجى ملء الحقول الـ 13 بدقة لتحديد متطلبات فحص التربة والمدونات الهندسية الإلزامية لمشروعك وفقاً للوائح العراقية.",
    "lbl_gov": "1. المحافظة",
    "lbl_district": "2. القضاء / الناحية",
    "lbl_zoning": "3. تصنيف جنس العقار (البلدية)",
    "lbl_plot": "4. رقم القطعة والمقاطعة",
    "lbl_area": "5. المساحة الكلية للأرض (متر مربع)",
    "lbl_built_area": "6. مساحة البناء الطابقي (متر مربع)",
    "lbl_floors": "7. عدد الطوابق الكلي",
    "lbl_height": "8. الارتفاع الكلي للمبنى (متر)",
    "lbl_basement": "9. هل يحتوي المبنى على سرداب (قبو)؟",
    "lbl_offset_f": "10. الارتداد الأمامي القانوني (متر)",
    "lbl_offset_s": "11. الارتدادات الجانبية والخلفية (متر)",
    "lbl_adjacent": "12. طبيعة الملاصقة والأبنية المجاورة",
    "lbl_structure": "13. النظام الإنشائي المقترح للهيكل",
    
    # محرك اتخاذ القرار والرسائل
    "btn_trigger_compliance": "🚀 تشغيل محرك المطابقة الفوري وفحص القيود",
    "warning_empty_fields": "⚠️ يرجى ملء كافة البيانات الجغرافية والإنشائية الـ 13 أولاً؛ لا يمكن تشغيل محرك المطابقة على حقول فارغة!",
    "success_msg": "✅ تهانينا! المخطط الأولي مطابق تماماً لكافة قيود البناء والمدونات المعتمدة جغرافياً في بلدية المنطقة.",
    "error_msg": "❌ تم رصد مخالفات صريحة لشروط البناء والمدونات الوطنية! تم تجميد المعاملة وقفل شهادة التوصية بالإجازة إلكترونياً."
}
# 1. ألحق هذه المفاتيح في نهاية القاموس العربي (AR_DICTIONARY):
    "p2_title_insulation": "🧱 1. العزل الحراري وغلاف المبنى",
    "p2_title_hvac": "❄️ 2. أحمال التكييف والمنظومات",
    "p2_title_solar": "☀️ 3. تصميم منظومة الألواح الشمسية",
    "p2_lbl_material": "نوع مادة بناء الجدران الخارجية المعتمدة:",
    "p2_lbl_thickness": "سمك طبقة العزل الحراري المقترحة (ملم):",
    "p2_mat_1": "طابوق طيني اعتيادي (بدون عزل)",
    "p2_mat_2": "بلوك إسمنتي مجوف",
    "p2_mat_3": "طابوق مع ألواح بوليسترين عازل (XPS)",
    "p2_mat_4": "ثرمستون (AAC Blocks) عالي الكفاءة",
    "p2_res_u_value": "📊 نتائج التدقيق البرمجي لمعامل الانتقال الحراري (U-Value):",
    "p2_calc_u": "المعامل المحسوب للمبنى:",
    "p2_max_u": "الحد الأقصى لمدونة البلديات:",
    "p2_u_compliant": "✓ [مطابق للمدونة الوطنية] - غلاف المبنى يحقق الحماية الحرارية المطلوبة.",
    "p2_u_non_compliant": "❌ [مخالف للمدونة] - تسريب حراري عالٍ! يرجى إضافة ألواح عزل XPS أو استخدام الثرمستون.",
# 1. ألحق هذه المفاتيح في نهاية القاموس العربي (AR_DICTIONARY):
    "p3_tab_summary": "📉 التحليل الإحصائي العام للمشروع",
    "p3_tab_boq": "📋 جدول تفكيك المواد والكميات (BOQ)",
    "p3_lbl_total_area": "إجمالي المساحة الطابقية للحصر:",
    "p3_lbl_green_score": "مؤشر البناء الأخضر المستدام:",
    "p3_lbl_density": "الكثافة الحجمية التقديرية للمواد:",
    "p3_boq_title": "📋 تفكيك جزيئات المواد والمكونات المستخرجة هندسياً",
    "p3_boq_notice": "*تم استخراج هذه الكميات الحجمية آلياً عبر محرك قراءة ملفات الـ Revit والـ AutoCAD في الـ Sandbox.*",
    "p3_col_code": "رمز العنصر",
    "p3_col_desc": "تفاصيل مادة البناء (الجزئيات الدقيقة)",
    "p3_col_qty": "الكمية المحصورة",
    "p3_col_unit": "الوحدة الهندسيّة",
    "p3_item_conc": "خرسانة مسلحة جاهزة مقاومة للأملاح والكبريتات (C30/37) للأسس",
    "p3_item_steel": "قضبان حديد تسليح عالي المقاومة (Grade 60) مشوه إنشائياً",
    "p3_item_brick": "طابوق طيني عراقي صنف (أ) مطابق للمواصفة القياسية رقم 25",
    "p3_item_ins": "ألواح عزل حراري من البوليسترين المبثوق (XPS) بسمك 5سم לגدران غلاف المبنى",
    "p3_item_solar": "منظومة خلايا شمسية كهروضوئية (Tier 1 Mono-PERC) بقدرة حسابية معتمدة",
    "p3_unit_m3": "متر مكعب",
    "p3_unit_ton": "طن متري",
    "p3_unit_count": "عدد (طابوقة)",
    "p3_unit_m2": "متر مربع",
    "p3_unit_panel": "لوح شمسّي",
    "p3_btn_pdf": "📥 إصدار وحفظ جدول الكميات المركزي والمواد (PDF BOQ Report)",

# 2. قاموس المصطلحات والـ 13 حقل باللغة الإنكليزية
EN_DICTIONARY = {
    "platform_title": "Iraqi Green Construction Data Platform",
    "platform_sub": "Digital Governance & Environmental Compliance",
    "nav_title": "🎛️ Platform Sovereign Control Panel",
    "current_location": "Current Location",
    "lang_label": "Language",
    
    "btn_portal_1": "🚪 Portal 1\nZoning & Soil Test",
    "btn_portal_2": "🌱 Portal 2\nEnergy & Green Score",
    "btn_portal_3": "📊 Portal 3\nCentral Materials BOQ",
    "btn_portal_4": "🗺️ Portal 4\nIraq GIS Map View",
    "btn_portal_5": "💳 Portal 5\nFinance & Payback",
    "btn_portal_6": "🦺 Portal 6\nField Site Safety",
    
    "side_title": "📊 Live Indicators Panel",
    "compliance_score": "Engineering Compliance",
    "integrity_score": "Structural Integrity",
    "energy_score": "Energy Score",
    
    "user_unregistered": "Unregistered Account",
    "user_action_verify": "Click to Verify Identity",
    "drawer_title": "🔐 Documentation & Legal Accountability Portal",
    "drawer_desc": "Official IDs must be uploaded to bear full legal accountability for the data and engineering blueprints.",
    "lbl_user_name": "User's Full Quadruple Name:",
    "lbl_user_role": "Technical Role in the Project:",
    "lbl_national_id": "National Unified ID Number (12 Digits):",
    "lbl_syndicate_id": "Valid Iraqi Engineers Syndicate ID Number:",
    "lbl_upload_avatar": "Upload Your Official Profile Photo (PNG/JPG):",
    "btn_submit_auth": "🔒 Approve, Verify Identity & Launch Sovereign Permissions",
    "badge_verified": "🛡️ Account Verified Sovereignly and النقابية | Professional Verified",
    "badge_desc": "Approved Rank: Licensed Consultant Engineer",
    "crypto_notice": "*Fields are encrypted military-grade via AES-256 to protect personal data confidentiality.*",
    "btn_reset": "🔄 Logout & Reset Empirical Log",
    
    "title_p1": "📋 Portal 1: Site Analysis & Municipal Constraints",
    "desc_p1": "Please fill out the 13 fields accurately to determine soil test requirements and mandatory engineering codes for your project in accordance with Iraqi regulations.",
    "lbl_gov": "1. Governorate",
    "lbl_district": "2. District / Sub-district",
    "lbl_zoning": "3. Land Zoning Type (Municipality)",
    "lbl_plot": "4. Plot & Sector Number",
    "lbl_area": "5. Total Land Area (sqm)",
    "lbl_built_area": "6. Built-up Footprint Area (sqm)",
    "lbl_floors": "7. Total Number of Floors",
    "lbl_height": "8. Total Building Height (meters)",
    "lbl_basement": "9. Does the building contain a basement?",
    "lbl_offset_f": "10. Legal Front Offset (meters)",
    "lbl_offset_s": "11. Side and Rear Offsets (meters)",
    "lbl_adjacent": "12. Type of Adjacent Buildings",
    "lbl_structure": "13. Proposed Structural System",
    
    "btn_trigger_compliance": "🚀 Trigger Instant Compliance Engine & Check Constraints",
    "warning_empty_fields": "⚠️ Please fill out all 13 geographical and structural fields first; the compliance engine cannot run on empty fields!",
    "success_msg": "✅ Congratulations! The initial blueprint complies with all building restrictions and approved national codes.",
    "error_msg": "❌ Explicit violations detected against municipal zoning and national codes! File frozen and recommendation certificate locked electronically."
}
# 2. ألحق هذه المفاتيح في نهاية القاموس الإنكليزي (EN_DICTIONARY):
    "p2_title_insulation": "🧱 1. Thermal Insulation & Building Envelope",
    "p2_title_hvac": "❄️ 2. HVAC Cooling Loads & Systems",
    "p2_title_solar": "☀️ 3. Solar PV System Design",
    "p2_lbl_material": "Approved External Wall Construction Material:",
    "p2_lbl_thickness": "Proposed Thermal Insulation Thickness (mm):",
    "p2_mat_1": "Standard Clay Brick (No Insulation)",
    "p2_mat_2": "Hollow Concrete Block",
    "p2_mat_3": "Clay Brick with XPS Insulation Boards",
    "p2_mat_4": "High-Efficiency Aerated Autoclaved Concrete (AAC)",
    "p2_res_u_value": "📊 Thermal Transmittance (U-Value) Audit Results:",
    "p2_calc_u": "Calculated U-Value for the Building:",
    "p2_max_u": "Maximum Limit for Municipal Code:",
    "p2_u_compliant": "✓ [Compliant with National Code] - The building envelope achieves required thermal protection.",
    "p2_u_non_compliant": "❌ [Non-Compliant] - High thermal leakage! Please add XPS insulation boards or use AAC blocks.",
# 2. ألحق هذه المفاتيح في نهاية القاموس الإنكليزي (EN_DICTIONARY):
    "p3_tab_summary": "📉 General Project Statistical Analysis",
    "p3_tab_boq": "📋 Bill of Quantities & Material Breakdown (BOQ)",
    "p3_lbl_total_area": "Total Built-up Area for BOQ:",
    "p3_lbl_green_score": "Sustainable Green Building Index:",
    "p3_lbl_density": "Estimated Volumetric Material Density:",
    "p3_boq_title": "📋 Deconstruction of Engineering Extracted Materials",
    "p3_boq_notice": "*These volumetric quantities were automatically extracted via the CAD/Revit BIM ingestion engine inside the Sandbox.*",
    "p3_col_code": "Item Code",
    "p3_col_desc": "Material & Element Specifications (Granular Details)",
    "p3_col_qty": "Extracted Quantity",
    "p3_col_unit": "Engineering Unit",
    "p3_item_conc": "Ready-mix reinforced concrete, sulfate-resistant (C30/37) for foundations",
    "p3_item_steel": "High-tensile deformed steel reinforcement rebars (Grade 60) structural",
    "p3_item_brick": "Iraqi clay bricks Class (A) compliant with National Standard No. 25",
    "p3_item_ins": "Extruded polystyrene (XPS) thermal insulation boards 5cm thick for building envelope",
    "p3_item_solar": "Photovoltaic solar panel system (Tier 1 Mono-PERC) approved structural capacity",
    "p3_unit_m3": "Cubic Meter (m³)",
    "p3_unit_ton": "Metric Ton (Ton)",
    "p3_unit_count": "Pcs (Bricks)",
    "p3_unit_m2": "Square Meter (m²)",
    "p3_unit_panel": "Solar Panel",
    "p3_btn_pdf": "📥 Export and Save Central Bill of Quantities (PDF BOQ Report)",

# 3. قاموس المصطلحات والـ 13 حقل باللغة الكردية الصافية
KU_DICTIONARY = {
    "platform_title": "سەکۆی بیناسازی بەردەوام",
    "platform_sub": "حوکمڕانی دیجیتاڵی و پابەندبوونی ژینگەیی",
    "nav_title": "🎛️ لۆگۆی کۆنترۆڵی سیادی سەکۆکە",
    "current_location": "شوێنی ئێستا",
    "lang_label": "زمان",
    
    "btn_portal_1": "🚪 دەروازەی ١\nپشکنینی خاک",
    "btn_portal_2": "🌱 دەروازەی ٢\nوزە و بەردەوامی",
    "btn_portal_3": "📊 دەروازەی ٣\nکۆکردنەوەی ماددەکان",
    "btn_portal_4": "🗺️ دەروازەی ٤\nنەخشەی جی ئێس",
    "btn_portal_5": "💳 دەروازەی ٥\nدارایی و قازانج",
    "btn_portal_6": "🦺 دەروازەی ٦\nسەلامەتی مەیدانی",
    
    "side_title": "📊 پانێڵی نیشاندەرە زیندووەکان",
    "compliance_score": "گونجانی ئەندازیاری",
    "integrity_score": "سەلامەتی پێکهاتەیی",
    "energy_score": "بەردەوامی وزە",
    
    "user_unregistered": "هەژماری تۆمارنەکراو",
    "user_action_verify": "کلیک بکە بۆ پشتڕاستکردنەوەی ناسنامە",
    "drawer_title": "🔐 دەروازەی بەڵگەنامە و بەرپرسیارێتی یاسایی",
    "drawer_desc": "پێویستە ناسنامە فەرمییەکان بەرزبکرێنەوە بۆ لەئەستۆگرتنی بەرپرسیارێتی یاسایی تەواو لەسەر زانیاری و نەخشە ئەندازیارییەکان.",
    "lbl_user_name": "ناوی چوارینەی تەواوی بەکارهێنەر:",
    "lbl_user_role": "ڕۆڵی تەکنیکی لە پڕۆژەکەدا:",
    "lbl_national_id": "ژمارەی ناسنامەی نیشتمانی یەکگرتوو (١٢ ژمارە):",
    "lbl_syndicate_id": "ژمارەی ناسنامەی کارای سەندیکای ئەندازیارانی عێراق:",
    "lbl_upload_avatar": "وێنەی پرۆفایلی فەرمی خۆت بەرزبکەرەوە (PNG/JPG):",
    "btn_submit_auth": "🔒 پەسەندکردن، پشتڕاستکردنەوەی ناسنامە و دەستپێکردنی مۆڵەتە سیادییەکان",
    "badge_verified": "🛡️ هەژمارەکە بە شێوەیەکی سیادی و سەندیکایی پشتڕاستکراوەتەوە",
    "badge_desc": "پلەی پەسەندکراو: ئەندازیاری ڕاوێژکاری مۆڵەتپێدراو",
    "crypto_notice": "*خانەکان بە شێوازی سەربازی لە ڕێگەی AES-256ـەوە کۆدکراون بۆ پاراستنی نهێنی زانیارییە کەسییەکان.*",
    "btn_reset": "🔄 چوونەدەرەوە و تصفیرکردنی تۆماری تاقیکاری",
    
    "title_p1": "📋 دەروازەی یەکەم: شیکردنەوەی شوێن و سنووردارکردنی شارەوانی",
    "desc_p1": "تکایە ١٣ خانەکە بە دروستی پڕبکەرەوە بۆ دیاریکردنی پێویستییەکانی پشکنینی خاک و کۆدەکانی ئەندازیاری زۆرەملێ بۆ پڕۆژەکەت بەپێی ڕێساکانی عێراق.",
    "lbl_gov": "١. پارێزگا",
    "lbl_district": "٢. قەزا / ناحیە",
    "lbl_zoning": "٣. پۆلێنکردنی زەوی (شارەوانی)",
    "lbl_plot": "٤. ژمارەی پارچە زەوی و کەرت",
    "lbl_area": "٥. ڕووبەری گشتی زەوی (مەتر دووجا)",
    "lbl_built_area": "٦. ڕووبەری بیناسازی نهۆمی (مەتر دووجا)",
    "lbl_floors": "٧. ژمارەی گشتی نهۆمەکان",
    "lbl_height": "٨. بەرزی گشتی بیناکە (مەتر)",
    "lbl_basement": "٩. ئایا بیناکە ژێرزەمینی تێدایە؟",
    "lbl_offset_f": "١٠. کشانەوەی پێشەوەی یاسایی (مەتر)",
    "lbl_offset_s": "١١. کشانەوەی تەنیشت و دواوە (مەتر)",
    "lbl_adjacent": "١٢. سروشتی تەنیشت و بینا هاوسێیەکان",
    "lbl_structure": "١٣. سیستەمی پێکهاتەیی پێشنیارکراو بۆ چوارچێوەکە",
    
    "btn_trigger_compliance": "🚀 دەستپێکردنی بزوێنەری هاوتاکردنی دەستبەجێ و پشکنینی بەربەستەکان",
    "warning_empty_fields": "⚠️ تکایە سەرەتا سەرجەم خانە جوگرافی و پێکهاتەیییەکانی ١٣ پڕبکەرەوە؛ بزوێنەری هاوتاکردن ناتوانێت لەسەر خانەی خاڵی کاربکات!",
    "success_msg": "✅ پیرۆزە! نەخشەی سەرەتایی بە تەواوی هاوتایە لەگەڵ سەرجەم بەربەستەکانی بیناسازی و کۆدە پەسەندکراوەکان.",
    "error_msg": "❌ سەرپێچی ئاشکرا لە مەرجەکانی بیناسازی و کۆدە نیشتمانییەکان دۆزرایەوە! مامەڵەکە بەسترا و بڕوانامەی ڕاسپاردە بە شێوەی ئەلیکترۆنی قفڵکرا."
}
# 3. ألحق هذه المفاتيح في نهاية القاموس الكردي (KU_DICTIONARY):
    "p2_title_insulation": "🧱 ١. دابڕانی گەرمی و تێکەڵکردنی بیناکە",
    "p2_title_hvac": "❄️ ٢. بارەکانی ساردکردنەوەی HVAC و سیستەمەکان",
    "p2_title_solar": "☀️ ٣. دیزاینی سیستەمی سۆلار PV",
    "p2_lbl_material": "ماددەی پەسەندکراو بۆ دروستکردنی دیواری دەرەکی:",
    "p2_lbl_thickness": "ئەستووری پێشنیارکراوی دابڕانی گەرمی (ملم):",
    "p2_mat_1": "خشتی قوڕی ستاندارد (بێ دابڕان)",
    "p2_mat_2": "بلۆکی کۆنکرێتی ناواڵا",
    "p2_mat_3": "خشت لەگەڵ تەختەی دابڕانی XPS",
    "p2_mat_4": "کۆنکرێتی هەوایی جۆری AAC (کۆنکرێتی سووک)",
    "p2_res_u_value": "📊 ئەنجامەکانی پشکنینی هاوکۆلکەی گواستنەوەی گەرمی (U-Value):",
    "p2_calc_u": "هاوکۆلکەی ئەژمارکراو بۆ بیناکە:",
    "p2_max_u": "بەرزترین سنووری ڕێپێدراوی شارەوانی:",
    "p2_u_compliant": "✓ [هاوتایە لەگەڵ کۆدی نیشتمانی] - تێکەڵکردنی بیناکە پارێزگاری گەرمی پێویست بەدەستدەهێنێت.",
    "p2_u_non_compliant": "❌ [هاوتاب نییە] - دزەکردنی گەرمی بەرزە! تکایە تەختەی دابڕانی XPS زیاد بکە یان بلۆکی سووکی AAC بەکاربهێنە."
# 3. ألحق هذه المفاتيح في نهاية القاموس الكردي (KU_DICTIONARY):
    "p3_tab_summary": "📉 شیکردنەوەی ئاماری گشتی پڕۆژەکە",
    "p3_tab_boq": "📋 خشتەی تێکشکاندنی ماددەکان و بڕەکان (BOQ)",
    "p3_lbl_total_area": "کۆی ڕووبەری نهۆمەکان بۆ حەسار:",
    "p3_lbl_green_score": "نیشاندەری بیناسازی سەوزی بەردەوام:",
    "p3_lbl_density": "چڕی قەبارەیی خەمڵێندراوی ماددەکان:",
    "p3_boq_title": "📋 تێکشکاندنی جزیاتی ماددەکان و پێکهاتە دەرهێنراوەکان",
    "p3_boq_notice": "*ئەم بڕە قەبارەییانە بە شێوەیەکی ئۆتۆماتیکی لە ڕێگەی بزوێنەری خوێندنەوەی AutoCAD و Revit BIM لە ناو Sandbox دەرهێنراون.*",
    "p3_col_code": "کۆدی بابەت",
    "p3_col_desc": "وردەکارییەکانی ماددەی بیناسازی (جزیاتی ورد)",
    "p3_col_qty": "بڕی دەرهێنراو",
    "p3_col_unit": "یەکەی ئەندازیاری",
    "p3_item_conc": "کۆنکرێتی چەکداری ئامادەکراو و دژە خوێ و سوڵفات (C30/37) بۆ بنەمەکان",
    "p3_item_steel": "شیشی کۆنکرێتی بەرگری بەرز (Grade 60) بۆ پێکهاتە",
    "p3_item_brick": "خشتی قوڕی عێراقی جۆری (أ) هاوتا لەگەڵ ستانداردی نیشتمانی ژمارە ٢٥",
    "p3_item_ins": "تەختەی دابڕانی گەرمی جۆری XPS بە ئەستووری ٥سم بۆ دیواری غیلافی بیناکە",
    "p3_item_solar": "سیستەمی خانەی سۆلار فۆتۆڤۆڵتاییک (Tier 1 Mono-PERC) بە توانای پەسەندکراو",
    "p3_unit_m3": "مەتر سێجا (م³)",
    "p3_unit_ton": "تەن (تەن)",
    "p3_unit_count": "دانە (خشت)",
    "p3_unit_m2": "مەتر دووجا (م²)",
    "p3_unit_panel": "تەختەی سۆلار",
    "p3_btn_pdf": "📥 دەرکردن و پاراستنی خشتەی بڕی ناوەندی و ماددەکان (PDF BOQ Report)"

# دمج القواميس الثلاثة بشكل نهائي ومستقل تماماً داخل السيرفر
DICTIONARY = {
    "ar": AR_DICTIONARY,
    "en": EN_DICTIONARY,
    "ku": KU_DICTIONARY
}

def get_text(key):
    """دالة قراءة لغة الجلسة وبث الكلمة المطابقة بالملي ثانية وبأمان تام"""
    current_lang = st.session_state.get("language", "ar")
    lang_dict = DICTIONARY.get(current_lang, DICTIONARY["ar"])
    return lang_dict.get(key, key)
